name: 'Notion translator'
description: 'A github action that translates fields in a notion database'
branding:
  icon: globe
  color: blue
inputs:
  notion_token:
    description: 'Notion API token'
    required: true
  translation_engine:
    description: 'Engine to use for translation (see: https://www.npmjs.com/package/translate)'
    required: true    
    default: 'google'
  translation_key:
    description: 'Key to use for translation if required (see: https://www.npmjs.com/package/translate)'
    required: false    
  translation_url:
    description: 'Url to use for translation if required (see: https://www.npmjs.com/package/translate)'
    required: false        
  database:
    description: 'Parent database to translate'
    required: true
  default_language_from:
    description: 'Language to assume to translate from if not provided in a column'
    required: true
    default: 'nl'
  default_language_to:
    description: 'Language to translate to'
    required: true
    default: 'en'
  field_to_translate:
    description: 'Database field name to translate'
    required: true
    default: 'Input'
  field_to_translate_status:
    description: 'Database field name to maintain translation status'
    required: true
    default: 'Status'
  field_to_translate_result:
    description: 'Database field name to add the translated result'
    required: true
    default: 'Result'
  field_to_translate_language:
    description: 'Database field name for input language of text'    
outputs:
  status: 
    description: 'The status of the translation'
runs:
  using: 'node16'
  main: 'dist/index.js'
