name: 'Notion mapper'
description: 'A github action that translates fields in a notion database to a relation'
branding:
  icon: globe
  color: blue
inputs:
  notion_token:
    description: 'Notion API token'
    required: true  
  database:
    description: 'Parent database to map columns in'
    required: true
  field_to_map_from:
    description: 'Database field map value from'
    required: true
    default: 'Input'
  field_to_map_to:
    description: 'Database field map value to (*must* be a relation to lookup database)'
    required: true
    default: 'Status'
  database_lookup:
    description: 'Database to use as the lookup table (*must be a relation to the `map_to` field!)'
    required: true
    default: 'Result'
  database_lookup_field:
    description: 'Database field name to use for the lookup (the `map_from` equivalent field above)'    
outputs:
  status: 
    description: 'The status of the mapping'
runs:
  using: 'node16'
  main: 'dist/index.js'
